### PR TITLE
143 include guests in total participant and packer counts

### PR DESCRIPTION
**Pull request by jadenar07**
## Description of this change
Adjusted the total participants to be an accurate representation of every person attending, including the guests. Added the proper variables to retrieve the information from the backend then made an exportable function to retrieve the real total participant count, including guests, for each event on different pages such as the event page and the event cards on the home page.
### Before this PR:
image### 
image
After this PR:
\<screenshot(s)>
Screenshot 2024-07-17 at 3 40 32 PM
image

### CODE REVIEW

**Comment by mattsahn** [comment]
@jadenar07, can you update the PR with description of changes and before/after screenshots, as well?

**Comment by jadenar07** [comment]
> @jadenar07, can you update the PR with description of changes and before/after screenshots, as well?

Updated the description

**Comment by mattsahn** [comment]
I notice some brief, odd behavior when loading or reloading the main page. This happens only in the deployment for this PR and not in the prod version. @jadenar07, do you see the same? I'm using chrome on windows. Haven't looked at the code closely, but imagine there's some difference or slight inefficiency. The results look fine, but see if you can track down the source of that. It's also a bit slower to refresh than the prod page.

image

**Comment by jadenar07** [comment]
> I notice some brief, odd behavior when loading or reloading the main page. This happens only in the deployment for this PR and not in the prod version. @jadenar07, do you see the same? I'm using chrome on windows. Haven't looked at the code closely, but imagine there's some difference or slight inefficiency. The results look fine, but see if you can track down the source of that. It's also a bit slower to refresh than the prod page.
> 
> image

image

That's quite odd, when I run the code on my end, it's showing a reload symbol for what I can assume is each event card. What's happening on mine is a slight bit different than yours. Before my change, I believe it only showed one reload symbol and was faster by a second or so. When I load into the events page with the volunteer table, it loads quickly. So the problem is likely related to some changes to the event card. I'll look at the code to try and track down the source of the inefficiency.

**Comment by mattsahn** [comment]
> That's quite odd, when I run the code on my end, it's showing a reload symbol for what I can assume is each event card. What's happening on mine is a slight bit different than yours. Before my change, I believe it only showed one reload symbol and was faster by a second or so. When I load into the events page with the volunteer table, it loads quickly. So the problem is likely related to some changes to the event card. I'll look at the code to try and track down the source of the inefficiency.

@jadenar07, any luck yet?

**Pull request closed without merging**
