### PR TITLE
64 some event page summary stats are incorrect

### PR DESCRIPTION
**Pull request by 6mp**
Addresses #64 

- Explicitly getting this data from airtable now to fix the discrepancies
-  Renamed a variable to match style

Looking at 02/11/2023

image

image

Looking at 03/04/2023

image

image

A more recent event, 06/10/2023

image

image

### CODE REVIEW

**Comment by 6mp** [comment]
I forgot to include total participants in the screenshots, I checked all of these dates and it lined up with what is displayed on the portal.

**Comment by mattsahn** [comment]
I see an issue with the driver count with the new version. When I run your branch, Feb 11 shows 5 drivers, instead of 6. The 5 seems to be based on "confirmed" drivers, but we want to show both confirmed and unconfirmed. We should exclude "Can't Come" drivers, so the number should be 6 i'm pretty sure.

image

Tagging @hgreenhut, too. Henry, you had asked about special groups count. For Feb 11, I see "St. Augustine's" and "Greenacres". The rest are "N/A". So, this count should be "2", not "3". It must be considering "N/A" as the 3rd special group to get that count?
image

**Comment by 6mp** [comment]
@mattsahn Ok, I will work on showing both unconfirmed and confirmed drivers.

The way I arrived at the special groups count was by checking in the airtable and just counting the number of special events, even if they don't have anyone coming.

 I can exclude the special groups who dont anyone coming if that is what you would like.

**Comment by mattsahn** [comment]
> The way I arrived at the special groups count was by checking in the airtable and just counting the number of special events, even if they don't have anyone coming.

Ok, I see. In that case, fine to leave as is for the special event count.

**Comment by 6mp** [comment]
To include unconfirmed drivers I will have to make a new rollup property in the Supplier Pickup Events table which will account for them. How should I go about doing this so it can be done on the live airtable also?

**Comment by hgreenhut** [comment]
@6mp The roll-up property it's pulling from is called "Only Driver Count" in Airtable, which is somewhat misleadingly named as it's really the count of confirmed volunteers who are only driving. The count of only packers is doing the same thing, pulling from a property filtered to only count confirmed records. To create a property for confirmed and unconfirmed drivers, you can just duplicate the only driver count property and remove the confirmed filter.  Unless I'm misunderstanding how it all works, I believe you can just make this property in the development base and live base and just name the properties the same.

**Comment by 6mp** [comment]
@hgreenhut Thank you that is exactly what I am doing.

**Comment by 6mp** [comment]
I made the appropriate changes in the test and prod airtables. The new fields are called `Only Distributor Count Including Unconfirmed` and `Only Driver Count Including Unconfirmed` respectively. I didn't edit the original fields since I dont want to disrupt anything that depends on them as they are.

**Comment by mattsahn** [comment]
I think we also need an "Driver and Distributor Count Including Unconfirmed", too. The "#Driving & Packing" count shows as zero, but there are 5 "Driving & Packing" signups for 7/29, they just haven't been confirmed yet.

image

current app shows the 5:
image

**Comment by 6mp** [comment]
I have addressed that in this commit @mattsahn

**Review by mattsahn — APPROVED** [review]
lgtm

**Pull request merged**
