### PR TITLE
Fixes issue of blank user in airtable by filtering returned users.

### PR DESCRIPTION
**Pull request by 6mp**

### CODE REVIEW

**Comment by mattsahn** [comment]
Per my comment in Monday, rather than doing all this filtering, I think we can just change this:

Users?filterByFormula=SEARCH(Username, "${username}") != ""

to this:

Users?filterByFormula=Username="${username}"

**Comment by 6mp** [comment]
I think the issue with the formula is the arguments are swapped, I changed it to `SEARCH("${username}",Username)` and it works as intended now without a second filter needed.

**Comment by 6mp** [comment]
Would you like me to use your formula and remove the second filter @mattsahn?

**Comment by mattsahn** [comment]
> Would you like me to use your formula and remove the second filter @mattsahn?

yeah, it's a bit more straightforward/concise looking, imo.

**Review by mattsahn — APPROVED** [review]
Looks good

**Pull request merged**
